---
title: "Intra_Taux"
author: "jonathankenjerry.lauture@uniq.edu"
date: "`r Sys.Date()`"
output:
  flexdashboard::flex_dashboard: null
runtime: shiny
resource_files:
- INTRA_TAUX DE CHANGE HAÏTI.Rproj
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(XML)
library(xml2)
library(rvest)
library(htmlTable)
library(dplyr)
library(shiny)
library(ggplot2)
library(plotly)
library(formattable)
```


```{r main, include=FALSE}
#Importation des données 
# Taux du jour HT 
url_tdj="https://www.brh.ht/taux-du-jour/"
dataread_tdj=rvest::read_html(url_tdj)
tableaux_tdj=rvest::html_table(dataread_tdj)
data.frame(tableaux_tdj)
TauxDuJour=data.frame(tableaux_tdj)


# Taux affichés par les banques HT  
url_tapb="https://www.brh.ht/taux-affiches-par-les-banques-et-les-agents-de-change-2/"
dataread_tapb=rvest::read_html(url_tapb)
tableaux_tapb=rvest::html_table(dataread_tapb)
data.frame(tableaux_tapb)
TauxAffichesParLesBanques=data.frame(tableaux_tapb)

# Rename

names(TauxAffichesParLesBanques)<-c("CATEGORIES","ACHATS","VENTES",'SPREAD')
names(TauxDuJour)<-c("CATEGORIES","ACHATS","VENTES",'SPREAD')


#Extraction

TAPB<-TauxAffichesParLesBanques[c(2:8),]

TDJ<-TauxDuJour[c(2,4,7),]

# Conversion

TAPB$CATEGORIES<-as.character(as.character(TAPB$CATEGORIES))
TAPB$ACHATS<-as.numeric(as.character(TAPB$ACHATS))
TAPB$VENTES<-as.numeric(as.character(TAPB$VENTES))
TAPB$SPREAD<-as.numeric(as.character(TAPB$SPREAD))
TAPB

TDJ$ACHATS<-as.numeric(as.character(TDJ$ACHATS))
TDJ$VENTES<-as.numeric(as.character(TDJ$VENTES))
TDJ$SPREAD<-as.numeric(as.character(TDJ$SPREAD))
TDJ

```


Taux de jour: Table
===============================================================================

### Tableau : Taux du jours

```{r echo=FALSE}
formattable(TDJ)

```

```{r echo=FALSE}
formattable(TAPB)

```


Taux du jour: Global 
==============================================================================

### Taux des différents marchés à l'achat et à la vente

```{r echo=FALSE}
#Graphe du Taux des différents marchés à l'achat

TDJA <- ggplot(data = TDJ, aes(x = CATEGORIES,y=ACHATS,fill = CATEGORIES)) + geom_col(just = 0)
plot1<-ggplotly(TDJA)

#Graphe du Taux des différents marchés à la vente

TDJV <- ggplot(data = TDJ, aes(x = CATEGORIES,y=VENTES,fill = CATEGORIES)) + geom_col(just = 0)
plot2<-ggplotly(TDJV)

# Afficher les graphiques dans une grille 
subplot(
  plot1, 
  plot2, 
  nrows = 2, 
  shareX = TRUE, 
  titleX = FALSE, 
  titleY = TRUE, 
  margin = 0.05
)

```



Taux du jour: Par Banque
================================================================================
### Taux pratiqué par les banques à la vente

```{r echo=FALSE}
fig <- plot_ly(TAPB, x = ~CATEGORIES, y = ~ACHATS,color ="yellow", type = 'bar', name = 'ACHATS')
fig <- fig %>% add_trace(y = ~VENTES, name = 'VENTES', color="blue")
fig <- fig %>% layout(yaxis = list(title = 'Taux du jour'),plot_bgcolor="black" , barmode = 'group')
fig

```
